### ISSUE TITLE
GitStack basic not able to add any user

### ISSUE THREAD

**Issue by poiuytrez** [smart-mobile-software/gitstack#132]
While the trial was not expired I was able to add as many users as I want (trial) ok.
Before the trial expired, I deleted the other(2) users so only the built in everyone and the one user(stadler) is in the users collection.
But when I import a new repository, then I get this message when I want to add ether stadler or everyone to the repository….

**Comment by poiuytrez** [comment]
Will be tested tomorrow.

**Comment by poiuytrez** [comment]
Bug test scenario : 
1. Add two users on a repository GitStack basic (or the number allowed by the license)
2. Try to create a repository
3. License error : number of maximum users reach. Please check http://gitstack.com/pricing/ to buy more users.

Side effect : the user "everyone" is also counted as an user for the license system.

**Comment by poiuytrez** [comment]
Fixed in : 40374b41fa2a89f75f9b103e7101b858978924b5

**Comment by a-swoboda** [comment]
In Version 2.2.4 this bug still exist I still have now repostries with 
the everyone user (no more possible)

**Comment by poiuytrez** [comment]
Could you describe how many users are allocated to other repositories? We would like to reproduce the same environment as yours.

**Comment by a-swoboda** [comment]
Hello poiuytrez,

 we have 9 repostries 

two users, no groups…

6 of the repostries where creted in the trial – they all have one user + everyone (2.2) (and I cannot add a second user

3 repostries where created after the trial

```
            1 of these 3 is created with 2.2 I could not add users to it (in 2.2) after updating to 2.2.4 I could add two users

            2 of them are created with 2.2.4  I cannot add a user to them (only the everyone)
```

With best regards 

Albrecht Swoboda 

Von: poiuytrez [mailto:notifications@github.com] 
Gesendet: Mittwoch, 31. Oktober 2012 13:18
An: smart-mobile-software/gitstack
Cc: Albrecht Swoboda
Betreff: Re: [gitstack] GitStack basic not able to add any user (#132) [faked-from]

Could you describe how many users are allocated to other repositories? We would like to reproduce the same environment as yours.

—
Reply to this email directly or view it on GitHub https://github.com/smart-mobile-software/gitstack/issues/132#issuecomment-9942527 . 

 https://github.com/notifications/beacon/2qjULh6T3O0r88T1AYvaC9sa-mrqPdYc0u_ulVu3xsxA7Sfit2mW9sMob_9Citr7.gif

**Comment by poiuytrez** [comment]
We have planned to try to reproduce the issue tomorrow. Feel free to add any additional comments in the meantime.

**Comment by poiuytrez** [comment]
The bug has been reproduced on GitStack 2.2.4 : 
When a repository contains 2 users, another repository cannot add another user (even if this one does not contain any user)
